サイトの紹介ページの更新
TKPaken/beginners pull request #116
Opened 2021-04-07 00:35 UTC by penguin-man

サイトの紹介ページを今年度のものに更新しました。一応去年のも残しておいた方がいいかなーと思ったので、新しく Home(new) というディレクトリを作り、そこに新しい md ファイルを入れておきました。
後はよしなにしてください...

2021-04-07 01:39 UTC, Osmium1008 requested changes
旧メインページは競プロ関連へのリンクの意味合いが強いのであまり残す必要はない気がします(少し変更して競プロ班のトップページにするとかはありですが)

2021-04-07 01:41 UTC, Osmium1008 commented
両方残すとして新メインページをindex.mdにして(旧はindex_old.mdとかに)
新:Home
旧:Home(old)
みたいに新メインページを優先する感じの方がいいかと

2021-04-07 04:53 UTC, 0xdef12e commented on docs/index.md
> +    <div class="quote">当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を使用しています。このGoogleアナリティクスはデータの収集のためにCookieを使用しています。このデータは匿名で収集されており、個人を特定するものではありません。<p></p><p>この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブ
これ、なんの違いが...？

2021-04-07 04:55 UTC, 0xdef12e commented on docs/index.md
> +    <div class="quote">当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を使用しています。このGoogleアナリティクスはデータの収集のためにCookieを使用しています。このデータは匿名で収集されており、個人を特定するものではありません。<p></p><p>この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブ
これ、なんの違いが...？

2021-04-07 11:06 UTC, penguin-man commented on docs/index.md
> +    <div class="quote">当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を使用しています。このGoogleアナリティクスはデータの収集のためにCookieを使用しています。このデータは匿名で収集されており、個人を特定するものではありません。<p></p><p>この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブ
間違えてコミットした時の名残です（たぶん何も変わってない）

2021-04-08 06:15 UTC, ageprocpp commented
これ，penguinman が fork しちゃってて手を出せないから，一回ここに同名のブランチ作って移してくれない？ @penguin-man

2021-04-08 07:07 UTC, merged